config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  jsonapi_resources :attendees
  jsonapi_resources :discounts
  jsonapi_resources :events
  jsonapi_resources :expenses
  jsonapi_resources :groups
  jsonapi_resources :guests
  jsonapi_resources :locations
  jsonapi_resources :members
  jsonapi_resources :photos
  jsonapi_resources :privates
  jsonapi_resources :sessions
  jsonapi_resources :teachers
  jsonapi_resources :transactions
  jsonapi_resources :users

  resources :purchases, only: [:create]
  resources :user_sessions, except: [:show, :update]
  get 's3-direct', to: 's3_direct#get'

  match '/404', via: :all, to: 'application#not_found'
  match '/500', via: :all, to: 'application#internal_server_error'
  match '*any', via: :all, to: 'application#not_found'
end

app/models/user.rb
class User < ActiveRecord::Base
  include PgSearch

  devise :invalidatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :group

  pg_search_scope :search_for, against: %w(name email)

  def avatar_url
    avatar
  end

  def self.from_oauth(auth)
    user = where(provider: auth[:provider], uid: auth[:uid]).first
    if user.nil?
      user = find_by_email(auth[:email])
      # Instantiate the user for the first time
      if user
        user.provider = auth[:provider]
        user.uid = auth[:uid]
        user.name = auth[:name]
        user.email = auth[:email]
        user.avatar = auth[:image]
        user.password = Devise.friendly_token[0,20]
        user.save
      end
    end
    user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/views/users/index.html.erb
<% content_for :title, "Users | Queer Tango Club" %>
<br>
<div class="frame">
  <section id="schedule">
    <h2>Users</h2>
    <hr>
    <nav>
      <%= link_to new_user_path do %>
        <%= icon("email-solid") %> Invite User
      <% end %>
      <hr class="thick">
    </nav>
    <div class="users">
      <div class="table">
        <div class="table-header thin-border-bottom">
          <div class="flex-row">
            <div class="table-cell name">Name</div>
            <div class="table-cell email">Email</div>
            <div class="table-cell login">Last Login</div>
          </div>
        </div>
        <div class="table-body block">
          <% @users.each do |user| %>
            <%= link_to user_path(user), class:"flex-row" do %>
              <div class="table-cell name"><%= user.name %></div>
              <div class="table-cell email"><%= user.email %></div>
              <div class="table-cell login"><%= user.last_sign_in_at.try(:strftime, '%b %e, %Y %l:%M%P') %></div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </section>
  <br>
  <br>
</div>

app/views/users/new.html.erb
<% content_for :title, "New User | Queer Tango Club" %>
<br>

<%= form_for(@user) do |f| %>
  <section id="new">
    <div class="frame">
      <header>
        <h2>
          <%= link_to('Users', users_path) %> <%= icon("right-chevron") %> New
        </h2>
        <%= f.submit "Invite" %>
      </header>
      <hr class="thick">
      <% if flash[:error] %>
        <ul class="alert">
          <% flash[:error].each do |message| %>
            <li><%= icon('alert-solid') %> <%= message %></li>
          <% end %>
        </ul>
      <% end %>
      <p>Provide an email address that's connected to a <a href="https://facebook.com">Facebook</a> or <a href="https://mail.google.com">Google</a> account.</p>
      <p>Once added, they'll be able to login to the site using their social network of choice.</p>
      <div class="flex-row half">
        <div>
          <div class="flex-column">
            <div>
              <%= f.label :email %>
              <%= f.email_field :email %>
            </div>
          </div>
        </div>
        <div>
        </div>
      </div>
    </div>
  </section>
<% end %>

app/views/users/show.html.erb
<% content_for :title, "#{@user.name || @user.email} | Queer Tango Club" %>
<br>
<div class="frame">
  <section id="user">
    <h2><%= link_to('Users', users_path) %> <%= icon("right-chevron") %> <%= @user.name || @user.email %></h2>
    <nav>
      <hr>
      <% if @user.user_sessions.size > 0 %>
        <%= link_to logout_user_path(@user) do %>
          <%= icon("cancel-solid") %> Sign out User
        <% end %>
        <hr class="thick">
      <% end %>
    </nav>
    <br>
    <div class="flex-row half">
      <div>
        <img src="<%= @user.avatar_url %>" alt="<%= @user.name || @user.email %>">
      </div>
      <div>
        <h3><%= @user.name %></h3>
        <p>
          <%= @user.email %>
        </p>
        <p>
          Last seen on <%= @user.last_sign_in_at.try(:strftime, '%B %e, %Y at %l:%M%P') %><br>
          Invited on <%= @user.created_at.try(:strftime, '%B %e, %Y at %l:%M%P') %>
        </p>
      </div>
    </div>
  </section>
  <br>
  <br>
</div>